version: 2
jobs:
  build:
   machine:
     python:
       version: 3.5.2

   steps:
      - run: echo 'hello beauty'
   dependencies:
     override:
       - pip install -r requirements.txt

   test:
     override:
       - nosetests tests/math-test.py
