version: 2
jobs:
  build:
   docker: # run the steps with Docker
     # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
     - image: circleci/python:3.6.4
   working_directory: ~/python-ci

   steps:
      - checkout
      - run: ls
      - run: pwd
      - run: python3 --version
      - run: pip3 install -r requirements.txt
      - run: nosetests test/math-test.py
   dependencies:
     override:
       - pip install -r requirements.txt

   test:
     override:
       - nosetests test/math-test.py
