version: 2
jobs:
  build:
   machine:
    python:
     version: 3.5.2
  steps:
   - run:
       name: no cuck
       command: |
          case "${CIRCLE_BRANCH}" in
          "develop")
          pip install -r requierements.txt
          ;;
          *)
          echo "no chuck to build"
          ;;
          esac
