machine:
  python:
    version: 3.5.2
test:
  override:
    - nosetests test/math-test.py
jobs:
  build:
    steps:
      - run:
        name: no cuck
        command: |
          case "${CIRCLE_BRANCH}" in
          "develop")
          pip install -r requierements.txt
          ;;
          *)
          echo "no chuck to build"
          ;;
          esac
